### ISSUE TITLE
example project does not compile

### ISSUE THREAD

**Issue by debris** [classapp/react-native-sensitive-info#13]

**Comment by mCodex** [comment]
Thank you for noticing. With some changes on react-native structure I should update the example project, but right now I'm afraid that I wont have time for this. However, PR are welcome :)

**Comment by anagar23** [comment]
@mCodex, still it's not working. error: bundling failed: Error: Unable to resolve module `react-native-sensitive-info` from `/Users/amitnagar/Documents/GitHub/sensitive/example/App.js`: Module `react-native-sensitive-info` does not exist in the Haste module map while bundling the example on Android device.
