### ISSUE TITLE
options is optional?

### ISSUE THREAD

**Issue by npomfret** [classapp/react-native-sensitive-info#17]
Hi.

Thanks for this project.  I'm just getting.  After reading _"Options" is a new parameter (optional)_ I tried calling `SInfo.deleteItem(_USER_ID_KEY)` but it failed with `RNSensitiveInfo. was called with 1 arguments but expects 2 arguments`.  Is the `options` parameter non-optional really?

**Comment by cthayer** [comment]
I'm getting the same error (when not passing the `options` parameter)
