### ISSUE TITLE
encryption breaks compile

### ISSUE THREAD

**Issue by npomfret** [classapp/react-native-sensitive-info#24]
The new android encryption stuff requires version 18 of the android API.  This isn't the default for react native project and renders this library unusable for those projects aim at 16.  

There's an encryption implementation [here](http://stackoverflow.com/questions/785973/what-is-the-most-appropriate-way-to-store-user-settings-in-android-application/6393502#6393502) that's compatible with 16.

**Comment by mCodex** [comment]
Thank you npomfret again, I reverted my last commit https://github.com/classapp/react-native-sensitive-info/commit/6e3c0248aeed7ca5c26a2e3c0ff2f706fe73bea6

**Comment by npomfret** [comment]
Thanks. I think we need a new npm release

**Comment by mCodex** [comment]
Yeah, doing it right now.

**Comment by mCodex** [comment]
About keystore, I think we should keep it in a different branch and if someone wants/needs to use they can get it there 🤔

**Comment by npomfret** [comment]
Sure. Or we implement a backward compatible version? One that works with a default RN build. And keeping a non-encrypted option so it's backward compatible would be good.

**Comment by mCodex** [comment]
Yeah, we can implement this one http://stackoverflow.com/questions/785973/what-is-the-most-appropriate-way-to-store-user-settings-in-android-application/6393502#6393502 which seems by far the best one.

**Comment by mCodex** [comment]
Yeah, we can implement that one you told before.

And here we go 5.0.1: https://www.npmjs.com/package/react-native-sensitive-info 🎉
