### ISSUE TITLE
Options aren't optional

### ISSUE THREAD

**Issue by sirnacnud** [classapp/react-native-sensitive-info#4]
When calling `getAllItems()` on Android with no parameters supplied, it will error out with:

```
com.facebook.react.bridge.NativeArgumentsParseException: RNSensitiveInfo.getAllItems got 2 arguments, expected 3
```

If I pass in an empty object it will throw the exception error:

```
com.facebook.react.bridge.NoSuchKeyException: couldn't find key sharedPreferencesName in dynamic object
```

I am basically forced to specify an object with a `sharedPreferencesName` property. This applies to all the methods on Android that take an options parameter.

**Comment by BogdanHossu** [comment]
Same on iOS, the options are not optional. Maybe, for the beginning update the readme file.
