### ISSUE TITLE
Update for breaking change in RN 0.40.0

### ISSUE THREAD

**Issue by randycoulman** [classapp/react-native-sensitive-info#9]
React Native 0.40.0 changed the location of header files on iOS, which is likely a breaking change for this project.

Unfortunately, my project is not yet in a place where I can easily verify that it is in fact a breaking change, but I wanted to get this issue on your radar.

See https://github.com/facebook/react-native/releases/tag/v0.40.0 for details.

**Comment by mCodex** [comment]
@randycoulman i'm proud to say that is not a problem anymore 😃  I've just updated RNSensitiveInfo to 4.0 and its fully compatible with RN0.40+. Thank you @hilkeheremans!

**Comment by hilkeheremans** [comment]
You're welcome! BTW, I didn't realize at the time of the PR, but it is possible to define your imports to be compatible with both `< RN 0.40` and `> 0.40` in the same version -- in that case it wouldnt require a semver major.

See also https://medium.com/@thisismissem/how-to-upgrade-react-native-modules-in-a-backwards-compatible-manner-a5b5c48d590c#.y41xx73x8
